#!/usr/bin/env bash
##############################################################################
# install.sh — One-command AlleycaTV player setup for a Raspberry Pi
#
# Run as root (or with sudo) on a fresh Raspberry Pi OS Lite install.
# The script will prompt you for the Pi's identity and network settings.
#
# Usage:
#   chmod +x install.sh
#   sudo ./install.sh
##############################################################################
set -euo pipefail

INSTALL_DIR="/opt/alleycatv"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "============================================"
echo "  AlleycaTV Player Setup"
echo "============================================"
echo ""

# ── Prompt for device configuration ──────────────────────────────────────────
read -rp "Pi ID (e.g. pi-lobby-1):                    " PI_ID
read -rp "Zone ID (e.g. zone-lobby):                " ZONE_ID
read -rp "AlleycaTV server IP (e.g. 192.168.1.100): " SERVER_IP
read -rp "MQTT broker IP (Mission Control):          " MQTT_IP
read -rp "MQTT username (leave blank if none):       " MQTT_USER
read -rsp "MQTT password (leave blank if none):      " MQTT_PASS
echo ""
read -rp "Photo interval (videos between photos, default 5): " PHOTO_INTERVAL
PHOTO_INTERVAL="${PHOTO_INTERVAL:-5}"

echo ""
echo "Configuration:"
echo "  PI_ID:          $PI_ID"
echo "  ZONE_ID:        $ZONE_ID"
echo "  SERVER_URL:     http://$SERVER_IP"
echo "  MQTT_BROKER:    $MQTT_IP"
echo "  MQTT_USER:      ${MQTT_USER:-<none>}"
echo "  PHOTO_INTERVAL: $PHOTO_INTERVAL"
echo ""
read -rp "Continue? [y/N]: " CONFIRM
[[ "${CONFIRM,,}" == "y" ]] || { echo "Aborted."; exit 0; }

# ── System packages ───────────────────────────────────────────────────────────
echo "Installing packages..."
apt-get update -qq
apt-get install -y --no-install-recommends \
    mpv python3 python3-pip python3-venv chromium-browser || \
apt-get install -y --no-install-recommends \
    mpv python3 python3-pip python3-venv chromium

# ── Create install directory ──────────────────────────────────────────────────
mkdir -p "$INSTALL_DIR"

# ── Python venv + dependencies ────────────────────────────────────────────────
echo "Setting up Python environment..."
python3 -m venv "$INSTALL_DIR/venv"
"$INSTALL_DIR/venv/bin/pip" install --upgrade pip -q
"$INSTALL_DIR/venv/bin/pip" install -r "$SCRIPT_DIR/requirements.txt" -q

# ── Copy player files ─────────────────────────────────────────────────────────
cp -r "$SCRIPT_DIR/alleycatv_player" "$INSTALL_DIR/"
chown -R "$(logname):$(logname)" "$INSTALL_DIR" 2>/dev/null || true

# ── Write config.py with user-supplied values ─────────────────────────────────
cat > "$INSTALL_DIR/alleycatv_player/config.py" <<EOF
"""AlleycaTV Pi player configuration — generated by install.sh"""
import os

PI_ID    = os.getenv("ALLEYCATV_PI_ID",   "$PI_ID")
ZONE_ID  = os.getenv("ALLEYCATV_ZONE_ID", "$ZONE_ID")

SERVER_URL   = os.getenv("ALLEYCATV_SERVER", "http://$SERVER_IP")
MQTT_BROKER  = os.getenv("ALLEYCATV_MQTT",      "$MQTT_IP")
MQTT_PORT    = int(os.getenv("ALLEYCATV_MQTT_PORT", "1883"))
MQTT_USER    = os.getenv("ALLEYCATV_MQTT_USER", "$MQTT_USER")
MQTT_PASS    = os.getenv("ALLEYCATV_MQTT_PASS", "$MQTT_PASS")

PHOTO_INTERVAL = int(os.getenv("ALLEYCATV_PHOTO_INTERVAL", "$PHOTO_INTERVAL"))
PHOTO_DURATION = int(os.getenv("ALLEYCATV_PHOTO_DURATION", "10"))
PLAYLIST_REFRESH_INTERVAL = int(os.getenv("ALLEYCATV_PLAYLIST_REFRESH", "300"))

MPV_SOCKET_PATH = os.getenv("ALLEYCATV_MPV_SOCKET", "/tmp/alleycatv-mpv.sock")
STATUS_INTERVAL = int(os.getenv("ALLEYCATV_STATUS_INTERVAL", "30"))

TOPIC_PREFIX   = "alleycatv"
TOPIC_STATUS   = f"{TOPIC_PREFIX}/pi/{PI_ID}/status"
TOPIC_ZONE_CMD = f"{TOPIC_PREFIX}/zone/{ZONE_ID}/cmd/#"
TOPIC_PI_CMD   = f"{TOPIC_PREFIX}/pi/{PI_ID}/cmd/#"
MEDIA_BASE_URL = f"{SERVER_URL}/media"
EOF

# ── systemd service ───────────────────────────────────────────────────────────
echo "Installing systemd service..."
cp "$SCRIPT_DIR/alleycatv-player.service" /etc/systemd/system/
systemctl daemon-reload
systemctl enable alleycatv-player
systemctl start alleycatv-player

echo ""
echo "============================================"
echo "  Install complete!"
echo "============================================"
echo "Service status:"
systemctl status alleycatv-player --no-pager || true
echo ""
echo "View logs:    journalctl -u alleycatv-player -f"
echo "Edit config:  $INSTALL_DIR/alleycatv_player/config.py"
echo "Restart:      sudo systemctl restart alleycatv-player"
