# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alleycatv.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'alleycatv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61lleycatv.proto\"\xa6\x01\n\x0bPiStatusMsg\x12\r\n\x05pi_id\x18\x01 \x01(\t\x12\x0c\n\x04zone\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x14\n\x0c\x63urrent_file\x18\x04 \x01(\t\x12\x16\n\x0eplaylist_index\x18\x05 \x01(\x05\x12\n\n\x02ip\x18\x06 \x01(\t\x12\x0e\n\x06uptime\x18\x07 \x01(\x03\x12\x0e\n\x06online\x18\x08 \x01(\x08\x12\x11\n\tnext_file\x18\t \x01(\t\"\t\n\x07PlayCmd\"\t\n\x07StopCmd\" \n\x0cInterruptCmd\x12\x10\n\x08\x66ile_url\x18\x01 \x01(\t\"\x13\n\x11ReloadPlaylistCmd\"\x1e\n\x0cSetVolumeCmd\x12\x0e\n\x06volume\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alleycatv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PISTATUSMSG']._serialized_start=20
  _globals['_PISTATUSMSG']._serialized_end=186
  _globals['_PLAYCMD']._serialized_start=188
  _globals['_PLAYCMD']._serialized_end=197
  _globals['_STOPCMD']._serialized_start=199
  _globals['_STOPCMD']._serialized_end=208
  _globals['_INTERRUPTCMD']._serialized_start=210
  _globals['_INTERRUPTCMD']._serialized_end=242
  _globals['_RELOADPLAYLISTCMD']._serialized_start=244
  _globals['_RELOADPLAYLISTCMD']._serialized_end=263
  _globals['_SETVOLUMECMD']._serialized_start=265
  _globals['_SETVOLUMECMD']._serialized_end=295
# @@protoc_insertion_point(module_scope)
